CREATE TABLE current_context (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    School_Year INT(2) NOT NULL, -- e.g., 24 for 2024-25
    Term ENUM('S1','S2','YR') NOT NULL,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);