CREATE TABLE IF NOT EXISTS enrollments (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Student_ID INT NOT NULL,
  Class_ID INT NOT NULL,
  FOREIGN KEY (Student_ID) REFERENCES students(ID) ON DELETE CASCADE,
  FOREIGN KEY (Class_ID) REFERENCES classes(ID) ON DELETE CASCADE,
  UNIQUE (Student_ID, Class_ID)
);
